ticket/urls.py
from django.urls import path

from ticket.views import firstpageview
from ticket.views import filmlistview
from ticket.views import Tozihfilm
from ticket.views import Sinama
from ticket.views import Sanslist
from ticket.views import aboutview
from ticket.views import SignUpView
from ticket.views import Profileview



urlpatterns = [

    path('first/',firstpageview.as_view(), name='firstpage'),
    path('film/<int:janer_id>/',filmlistview.as_view()),
    path('tozih/<slug:slug>/', Tozihfilm.as_view()),
    path('sinama/', Sinama.as_view(), name='sinama'),
    path('sanslist/', Sanslist.as_view(), name='sans'),
    path('about/',aboutview.as_view(), name='about'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/profile/', Profileview.as_view(), name='profile'),
]

web/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls"),name='accounts'),
    path('',include('ticket.urls'), name='ticket'),
    path('api/',include('rest_api.urls'), name='api'),
]


#  برای زمانی است که عکس را آپلود کردید و نمایش داده نمیشود
#   با کد زیر نمایش داده میشود و برای زمانی است که هنوز دیباگ تنظیمات فعال است
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ticket/models.py
from django.db import models
from .extensions.utils import jalali_datetime


# Create your models here.

class Janer(models.Model):
    class Meta:
        verbose_name = 'ژانر ها'
        verbose_name_plural = 'ژانر ها'

    janer_name = models.CharField(max_length=200, verbose_name='نوع ژانر')
    janer_tozihat = models.CharField(max_length=200, verbose_name='معرفی ژانر')
    image_janer = models.ImageField(upload_to='janerimages', verbose_name='عکس ژانر', null=True)

    def __str__(self):
        return self.janer_name


class Film(models.Model):
    class Meta:
        verbose_name = 'فیلم ها'
        verbose_name_plural = 'فیلم ها'

    namber_film = models.CharField(max_length=100, null=True, verbose_name='سریال فیلم')
    name_janer = models.ForeignKey(to=Janer, on_delete=models.PROTECT, null=True, verbose_name='نوع ژانر')
    name_film = models.CharField(max_length=200, verbose_name='نام فیلم')
    karghardan=models.CharField(max_length=50,null=True,verbose_name=' کارگردان')
    name_bazigaran = models.CharField(max_length=200, verbose_name='نام بازیگران')
    tozihat = models.CharField(max_length=1000, verbose_name='درباره فیلم')
    time_film = models.DateTimeField(null=True , verbose_name='زمان تولید فیلم')
    image_film = models.ImageField(upload_to='filmimages', verbose_name='عکس فیلم', null=True)
    film_time= models.CharField(max_length=100 , null=True , verbose_name='تایم فیلم')
    country_film = models.CharField(max_length=50 ,null=True , verbose_name='محصول کشور')
    z0= 1
    z9= 2
    z14=3
    z18=4
    z50=5
    z5=6
    age_choise = ((z0 , 'مناسب برای تمام سنین'),
                  (z5 , 'مناسب برای کودکان زیر 9 سال'),
                  (z9 , 'تماشا افراد زیر 9 سال ممنوع است'),
                  (z14 , 'تماشا افراد زیر 14 سال ممنوع است'),
                  (z18 , 'مناسب برای افراد بالای 18 سال'),
                  (z50 , 'تماشا برای افرادی که ناراحتی قلبی دارند ممنوع است'))
    age_film = models.IntegerField(choices=age_choise ,null=True , verbose_name='محدودیت های تماشا فیلم')


    def __str__(self):
        return self.name_film

    def jalalidatetime(self):
        return jalali_datetime(self.time_film)

    jalalidatetime.short_description = 'زمان تولید فیلم'



class Location (models.Model):
    class Meta:
        verbose_name = 'سینما ها'
        verbose_name_plural = 'سینما ها'
    a=1 ; b=2 ; c=3 ; d=4 ; e=5 ; f=6 ; g=7 ; h=8 ; i=9 ; j=10 ; k=11 ; l=12 ; m=13 ; n=14 ; o=15 ; p=16 ; q=17 ; r=18 ; s=19 ; t=20 ; u=21 ; v=22 ; w=23 ; x=24 ; y=25 ; z=26 ; aa=27 ; bb=28 ; cc=29 ; dd=30 ; ee=31
    ostan_choises = ((d , 'اصفهان'),(h , 'تهران'),(k , 'مشهد'),(q , 'شیراز'),(s , 'قم'),(bb , 'مرکزی'))
    ostan=models.IntegerField(choices=ostan_choises , verbose_name='استان ها')
    name_location=models.CharField(max_length=100, verbose_name='نام سینما')
    adress_location=models.CharField(max_length=300 , verbose_name='ادرس سینما')
    phone_location=models.CharField(max_length=11 , null=True, verbose_name='شماره تماس')

    def __str__(self):
        return '{} {}'.format (self.name_location,self.adress_location)




class sans(models.Model):
    class Meta:
        verbose_name = 'سانس ها'
        verbose_name_plural = 'سانس ها'

    namber_sans = models.CharField(max_length=100, null=True, verbose_name='سریال سانس')
    film_sans = models.ForeignKey(to=Film, on_delete=models.PROTECT, null=True, verbose_name='فیلم سانس')
    time_sans = models.DateTimeField(verbose_name='زمان سانس')
    local_sans = models.ForeignKey(to= Location, on_delete=models.PROTECT, null=True , verbose_name='مکان سانس')
    start = 1
    end = 2
    blit = 3
    kansel= 4
    endblit= 5
    status_choices = ((start, ' سانس شروع شده است'),
                      (end, ' سانس تمام شده است'),
                      (blit, 'در حال فروش بلیط'),
                      (kansel, ' سانس کنسل شده است'),
                      (endblit, 'بلیط تمام شده است'))
    status_sans = models.IntegerField(choices=status_choices, verbose_name='وضعیت سانس')
    zarfiat_sans = models.IntegerField(verbose_name='ظرفیت سانس')
    price_sans = models.CharField(max_length=30,default='تومان' , verbose_name= 'هزینه سانس',null=True)

    def __str__(self):
        return '{} {}'.format (self.film_sans,self.local_sans)

    def jalalidatetime(self):
        return jalali_datetime(self.time_sans)

    jalalidatetime.short_description = 'زمان سانس'



class Profile(models.Model):
    class Meta:
        verbose_name = 'پروفایل ها'
        verbose_name_plural = 'پروفایل ها'

    first_name = models.CharField(max_length=100, verbose_name='نام')
    last_name = models.CharField(max_length=100, verbose_name='نام خانوادگی')
    Man = 1
    Male = 2
    jns_choices = ((Man, "مرد"),
                   (Male, "زن"))
    jens = models.IntegerField(choices=jns_choices, verbose_name='جنسیت', null=True)
    imail_name = models.CharField(max_length=100, null=True, verbose_name='ایمیل')
    adress_name = models.CharField(max_length=200, verbose_name='آدرس محل سکونت')
    phone_name = models.CharField(max_length=11, default='09', verbose_name='شماره تماس')
    image_name = models.ImageField(upload_to='profileimages', verbose_name='عکس پروفایل', null=True)

    def __str__(self):
        return self.imail_name

ticket/views.py
# Create your views here.

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Janer
from .models import Film
from .models import Location
from .models import sans
from .models import Profile


from django.views.generic import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


class firstpageview(LoginRequiredMixin,TemplateView):
    template_name = 'ticket/firstpage.html'

    def get_context_data(self, *args, **kwargs):
        context = super(firstpageview, self).get_context_data(*args, **kwargs)
        context['filmi'] = Film.objects.all()
        return context


class filmlistview(LoginRequiredMixin,ListView):
    template_name = 'ticket/filmlist.html'
    model = Film

    def get_queryset(self, **kwargs):
        query = super().get_queryset(**kwargs)
        film_id = self.kwargs.get('janer_id')
        query = query.filter(name_janer__id=film_id)
        return query


class Tozihfilm(LoginRequiredMixin,DetailView):
    model = Film
    template_name = 'ticket/tozihfilm.html'
    slug_field = 'namber_film'


class Sinama (LoginRequiredMixin,TemplateView):
    template_name = 'ticket/locationlist.html'

    def get_context_data(self, **kwargs):
        context = super(Sinama, self).get_context_data(**kwargs)
        context['local'] = Location.objects.all()
        return context



class Sanslist(LoginRequiredMixin,ListView):
    model = sans
    template_name = 'ticket/sanslist.html'



class aboutview(TemplateView):
    template_name = 'ticket/about.html'

    def get_context_data(self, *args, **kwargs):
        context = super(aboutview, self).get_context_data(*args, **kwargs)
        # context['users'] = YourModel.objects.all()
        return context




from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'ticket/signup.html'


# class Profileview(TemplateView):
#     template_name = 'ticket/profile.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(Profileview, self).get_context_data(**kwargs)
#         context['pro'] = Profile.objects.all()
#         return context


from django.views.generic.edit import UpdateView
class Profileview (UpdateView):
    model = Profile
    fields = ['first_name', 'last_name' , 'imail_name' , 'phone_name' , 'adress_name']
    success_url = "/"
    template_name = 'ticket/profile.html'

    def get_object(self):
        return self.request.user

ticket/templates/ticket/about.html
{% extends "registration/base.html" %}
    

{% block 1 %}

    درباره ما چی میدانید؟ 

{% endblock 1 %}



{% block two %}

     <div class="container">
         <b>
            میخواهید ما را بیشتر بشناسید؟
         </b>
         <p>  </p>
         <p>  </p>
         <p>  </p>

         
         <p1>
             تمام تلاش کادر ما برای بهبودی و سهولت در انجام رزرو های شما کاربران عزیز است . پس اگر نظرات یا پیشنهاداتی داشتید میتوانید برای بهبودی سایت ما را همراهی کنید و ما از اینکه نظرات خود را ارائه میکنید خیلی خرسندیم
         </p>


         <b style="font-family: 'Shabnam', Tahoma ; font-size: 25px">قوانین و مقررات کلی</b>
         <h3 style="font-family: 'Shabnam', Tahoma ; font-size: 20px">عضویت و یا خرید شما در وب سایت و اپلیکیشن‌های سینما روز به معنی توافق شما با شرایط ذیل می باشد:</h3>
         <p>     </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">
1- خدمات و محتویات سایت سینما روز، صرفاً برای استفاده شخصی و غیر تجاری کاربران عرضه شده است. هرگونه سوء استفاده از این اطلاعات، پیگرد قانونی خواهد داشت. هیچ فرد حقیقی، حقوقی یا سایتی به هیچ عنوان نمی تواند از اطلاعات موجود در این سایت برای فروش، تولید مجدد و یا ایجاد ترافیک در سایت خود استفاده نماید. استفاده از محتویات سایت سینما روز برای سایت ها و وبلاگ های شخصی تنها به شرطی که منافع تجاری مدنظر نباشد، با ذکر منبع یا آدرس سایت مجاز می باشد.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">2- کاربران گرامی به سایت سینما روز اطمینان می دهند که از محتویات این سایت برای رسیدن به مقاصدی که برخلاف قوانین موضوعه یا شرایط استفاده از سینما روز می باشد، استفاده نخواهند کرد. آنها از سینما روز به گونه ای استفاده نخواهند کرد که باعث آسیب، از کار انداختن یا معیوب ساختن سایت شود. همچنین کاربران مجاز به دسترسی یا تلاش برای دسترسی به اطلاعات یا محتویاتی که تعمداً به طور متعارف در دسترس مخاطبین قرار نگرفته واز طریق صفحات سایت ارائه نشده اند، نیستند.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">3- مطالب سایت سینما روز ممکن است شامل لینک هایی به سایت های دیگرباشد. سینما روز این لینک ها را برای سهولت کاربران فراهم کرده است و وجود هر یک از این لینک ها به معنی تأیید یا ارتباط ما با اداره کنندگان آنها نیست. این سایت ها تحت کنترل سینما روز نیستند و سینما روز هیچ مسئولیتی در قبال محتویات این سایتها، از جمله لینک ها و عکسها، ندارد. کاربران توافق می کنند مسئولیت هرگونه خسارت و آسیب احتمالی به رایانه شان از طریق ویروس یا فایل های مخرب دیگر که می تواند ناشی از دریافت و استفاده از داده ها و فایل های متعلق به سایت های لینک شده در سینما روز باشد، خود برعهده خواهند داشت.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">4- وب سایت سینما روز، تحت هیچ شرایطی، مسئولیت تأخیر یا عدم کارکرد سایت را که ممکن است ناشی از عوامل طبیعی، نیروی انسانی، مشکلات اینترنتی، خرابی تجهیزات کامپیوتری، مخابراتی و غیره باشد، برعهده ندارد.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">5-  افراد برای عضویت در سایت سینما روز و خرید از آن باید به قسمت عضویت مراجعه کنند تا پس از وارد کردن اطلاعات خواسته شده، کد تأیید عضویت برای آنان ارسال شود. کاربران با وارد کردن کد، عضویت خود را تأیید می کنند.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">6- کاربر موظف است اطلاعات شخصی واقعی و صحیح خود را در سایت وارد نماید. سینما روز مسئولیتی در قبال هرگونه مشکل احتمالی که در اثر ارائه اطلاعات غلط از طرف کاربر به این سایت، ایجاد شده است، ندارد. </p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">7- به دلیل آنکه در برخی از موارد احراز هویت خریدار از طریق نام و نام خانوادگی ارائه شده در سایت امکانپذیر است، مسئولیت هرگونه مغایرت مشخصات فوق با هویت واقعی عضو برعهده خود افراد بوده و شرکت هیچ گونه مسئولیتی در خصوص مغایرت های احتمالی ندارد.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">8- کلمه عبور هر کاربر، محرمانه بوده و مسئولیت حفاظت از آن به عهده خود او می باشد.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">9- رسیدهایی که پس از خرید برای کاربران عضو ارسال می شود، دارای نام و مشخصات است اما کاربر باید از رسید یا کد دریافتی مراقبت نماید و چنانچه به هر دلیلی رسید مربوطه مفقود شود و یا شخص دیگری از آن استفاده کند، شرکت در این زمینه هیچ مسئولیتی ندارد.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">10- سیستم پرداخت ما از طریق درگاه الکترونیکی بانک های معتبر کشور انجام می شود، بنابراین سینما روز مسئول مشکلات احتمالی پرداخت بانک ها نخواهد بود.</p>
         <p>    </p>
         <p style="font-family: 'Shabnam', Tahoma ; font-size: 15px">11- چنانچه مشتری در مهلت تعیین شده از بلیت خود استفاده ننماید، سینما روز مسئولیتی در قبال از بین رفتن فرصت مشتری ندارد و وجه مسترد نخواهد شد.</p>
     
        </div>

{% endblock two %}

ticket/templates/ticket/filmlist.html
{% extends "registration/base.html" %}
    

{% block 1 %}

     فیلم ها  

{% endblock 1 %}



{% block two %}
<div class="row">
    {% for fullfilm in object_list %}

                        <div class="col-md-2">
                <div class="border" style="text-align: center">
                            <a href="/tozih/{{ fullfilm.namber_film }}"><img src="{{ fullfilm.image_film.url }}" class="img-responsive" style="width: 100% ; height: 200px"></a>
                    <a href="/tozih/{{ fullfilm.namber_film }}" style="text-decoration: none ; color: black">{{ fullfilm }}</a>
                </div>
                <p>  </p>
            </div>

    {% endfor %}
</div>

{% endblock two %}

ticket/templates/ticket/firstpage.html
{% extends "registration/base.html" %}
{#{% extends "ticket/layout.html" %}#}
{% load static %}

{% block 1 %}

    سینما سایت

{% endblock 1 %}



{% block two %}

    <div class="row">
    <img src="{% static 'ticket/images/bio1.png' %}" style="width: 100%;height: 200px" alt="none">
    <img src="{% static 'ticket/images/bio2.jpg' %}" style="width: 100%;height: 200px" alt="none">
    <P>   </P>
    {% if filmi %}
        {% for fullfilm in filmi %}

                <div class="col-md-2">
                    <div class="border" style="text-align: center">
                        <abbr title=" نوع فیلم : {{ fullfilm.name_janer }}
 کارگردان : {{ fullfilm.karghardan }}
 نام بازیگران : {{ fullfilm.name_bazigaran }}
 سال تولید : {{ fullfilm.time_film }}">
                        <a href="/tozih/{{ fullfilm.namber_film }}"><img src="{{ fullfilm.image_film.url }}" class="img-responsive" style="width: 100% ; height: 200px"></a>
                        </abbr>
                            <a href="/tozih/{{ fullfilm.namber_film }}" style="text-decoration: none ; color: black">{{ fullfilm }}</a>
                    </div>
                        <p>  </p>
                </div>

        {% endfor %}
    {% endif %}
    </div>
{% endblock two %}

ticket/templates/ticket/locationlist.html
{% extends "registration/base.html" %}


{% block 1 %}

    لیست سینماها

{% endblock 1 %}



{% block two %}



            <div class="card">
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table m-0">
                    <thead>
                    <tr>
                      <th style="text-align: right">نام سینما</th>
                      <th style="text-align: center">آدرس سینما</th>
                      <th style="text-align: left">شماره تماس</th>
                    </tr>
                    </thead>
                    <tbody>
                  {%  if local %}
                  {%  for fullocal in local %}
                    <tr>
                      <td style="text-align: right"><a href="#">{{ fullocal.name_location}}</a></td>
                      <td style="text-align: center">{{ fullocal.adress_location}}</td>
                      <td style="text-align: left"><span class="badge badge-success"></span>{{ fullocal.phone_location}}</td>
                    </tr>
                  {% endfor %}
                  {% endif %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>



{% endblock two %}

ticket/templates/ticket/profile.html
{% extends "registration/base.html" %}
{% load crispy_forms_tags %}

{% block 1 %}

    ایجاد پروفایل کاربری

{% endblock 1 %}



{% block two %}

<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>

{% endblock two %}

ticket/templates/ticket/sanslist.html
{% extends "registration/base.html" %}


{% block 1 %}

    لیست سانس ها

{% endblock 1 %}



{% block two %}

<div class="row">
    {% for fullsans in object_list %}
        <div class="col-md-4">
            <div class="product-thumb">
                <a href="#" style="text-decoration: none">

                    <div class="imageBox" style="text-align: center ; background-color: #ddd">

                        <p class="btn-secondary" style="text-align: center ; font-size: 30px ; color: #25cff2">{{ fullsans.film_sans }}</p>
                        <hr>
                        <p>{{ fullsans. }}</p>
                        <p style="text-align: center ; color: crimson">{{ fullsans.local_sans.name_location }}</p>
                        <p style="text-align: center ; color: #06357a ; font-size: 15px">{{ fullsans.local_sans.adress_location }}</p>

                        <p></p>
                        <p class="mdi mdi-timelapse time" style="text-align: center ; font-family: unset ; font-size: 13px ; color: #b02a37">
                            {{ fullsans.jalalidatetime }}
                        </p>
                        <p class="mdi mdi-cash price" style="text-align: center ; color: #d63384 ; font-size: 15px">
                            {{ fullsans.price_sans }}
                        </p>

                        <button
                                class="
                                {% if fullsans.status_sans == fullsans.start %}
                                btn btn-primary
                                {% elif fullsans.status_sans == fullsans.end %}
                                btn btn-danger
                                {% elif fullsans.status_sans == fullsans.blit %}
                                btn btn-dark
                                {% elif fullsans.status_sans == fullsans.kansel %}
                                btn btn-danger
                                {% elif fullsans.status_sans == fullsans.endblit %}
                                btn btn-danger
                                {% endif %}
                                ">
                            {{ fullsans.get_status_sans_display }}
                        </button>

                    </div>



                </a>
            </div>
        </div>

    {% endfor %}
</div>

{% endblock two %}

ticket/templates/ticket/signup.html
{% extends "registration/base.html" %}
{% load crispy_forms_tags %}


{% block 1 %}

    یک حساب کاربری جدید ایجاد کنید

{% endblock 1 %}



{% block two %}

    <form method="post">
    {% csrf_token %}

    <div class="row">
    <div class="container-fluid" style="float: right ; background-color: white ; width: 7in ; height: 5in">
        <b style="font-size: 30px">ایجاد حساب کاربری </b>
        <p>  </p>

        {{ form|crispy }}

        <p>  </p>
        <button type="submit" value="login" style="background-color: #198754">ایجاد حساب</button>
    <p>  </p>



        </div>
    </form>
    <p>   </p>
    <p>    </p>


{% endblock two %}

ticket/templates/ticket/tozihfilm.html
{% extends "registration/base.html" %}


{% block 1 %}

    توضیحات درباره فیلم

{% endblock 1 %}



{% block two %}

    <div class="row">
        <div class="container-fluid" style="float: right ; background-color: white ; width: 3in ; height: auto">
            <img src="{{ object.image_film.url }}" style="width: 250px ; height: 300px">
        </div>
        <div class="container-fluid" style="width: 70% ; height: auto">

            <b class="mdi mdi-film" style="font-family: 'Shabnam', Tahoma ; font-size: 30px ; color: #6a1a21"> {{ object.name_film }} </b>
            <p>    </p>
            <h1 class="mdi mdi-arrow-left-bold-circle" style="font-family: 'Shabnam', Tahoma ; font-size: 20px ; color: #ffc107"> {{ object.get_age_film_display }}</h1>
            <p style="color: white">  .  </p>
            <b style="font-family: 'Shabnam', Tahoma ; font-size: 19px"> کارگردان : {{ object.karghardan }}</b>
            <p>   </p>
            <h1 style="font-family: 'Shabnam', Tahoma ; font-size: 17px">  {{ object.film_time }} - {{ object.name_janer }} - محصول  {{ object.country_film }}</h1>
            <h1 style="font-family: 'Shabnam', Tahoma ; font-size: 17px">  {{ object.jalalidatetime }}</h1>
            <p style="color: white"> . </p>
            <b style="font-family: 'Shabnam', Tahoma ; font-size: 19px"> نام بازیگران  </b>
            <h1 style="font-family: 'Shabnam', Tahoma ; font-size: 18px"> {{ object.name_bazigaran }}</h1>
            <p style="color: white"> . </p>
            <b style="font-family: 'Shabnam', Tahoma ; font-size: 19px"> درباره فیلم  </b>
            <h1 style="font-family: 'Shabnam', Tahoma ; font-size: 18px">  {{ object.tozihat }}</h1>
            <p style="color: white">  .  </p>
            <hr>
            <div>
                <button class="mdi mdi-gesture-tap" style="float: left ; background-color: #198754 ; font-size: 20px"><a href="{% url 'sans' %}" style="font-size: 18px ; text-decoration: none; color: #101214">سانس ها</a></button>
                <button class="mdi mdi-bookmark" style="background-color: #0b7dda ; font-size: 18px">نشان کن</button>
                <button class="mdi mdi-thumb-up" style="background-color: #198754 ; font-size: 18px"></button>
                <button class="mdi mdi-thumb-down" style="background-color: #a52834 ; font-size: 18px"></button>
            </div>
        </div>
    </div>

{% endblock two %}